services:
  database:
    image: postgres:16
    container_name: postgresExamen
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saf3password
      POSTGRES_DB: examenDB
    volumes:
      - db:/var/lib/postgresql/data

  server:
    depends_on:
      - database
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:3001"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend

  client:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src

volumes:
  db:
